package com.pdsl.gherkin;

import com.pdsl.gherkin.models.GherkinFeature;
import com.pdsl.gherkin.parser.GherkinParserBaseListener;
import org.antlr.v4.runtime.CommonTokenStream;

import java.net.URI;
import java.util.Optional;

public abstract class PdslGherkinListener extends GherkinParserBaseListener {

    public abstract Optional<GherkinFeature> getGherkinFeature(URI featurePathOrId);

    /**
     * Sets the token stream for this listener.
     *
     * <p>This is required during the parse tree traversal to allow the listener
     * to look up hidden/off-channel tokens, such as Gherkin comments, which are
     * not attached to the primary AST nodes.
     *
     * @param tokens the {@link CommonTokenStream} generated by the lexer
     */
    public abstract void setTokenStream(CommonTokenStream tokens);
}
